language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install git+https://github.com/kernsuite-debian/sharedarray.git
  - pip install scipy
  - pip install -r requirements.txt 
# command to run tests
script: python convert.py --crop_size 128 --convert_directory data/train_tiny --extension tiff --directory data/train
